# Generated by Django 5.2 on 2025-05-01 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscribeVendor',
            fields=[
                ('subscribe_vendor_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('internal_api_key', models.CharField(max_length=255)),
                ('user_friendly_name', models.CharField(blank=True, default='', max_length=100)),
                ('vendor_name', models.CharField(max_length=100)),
                ('custom_arg', models.TextField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('vendor_redirect_url', models.TextField(blank=True, null=True)),
                ('vendor_cancel_url', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('store_type', models.CharField(choices=[('1', 'Stripe'), ('2', 'Paypal'), ('3', 'shopify'), ('4', 'Android'), ('5', 'iOS')], max_length=100)),
                ('amount', models.FloatField()),
                ('date', models.DateTimeField()),
                ('status', models.CharField(choices=[('1', 'Success'), ('2', 'Fail'), ('3', 'Cancelled')], max_length=100)),
                ('event_type', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionStatus',
            fields=[
                ('status_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('login_access_code', models.CharField(max_length=100)),
                ('subscription_id', models.CharField(max_length=200)),
                ('subscription_status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('subscribe_vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscription.subscribevendor')),
            ],
            options={
                'unique_together': {('subscription_id', 'login_access_code', 'subscribe_vendor')},
            },
        ),
    ]
