# Generated by Django 5.2 on 2025-05-03 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribevendor',
            name='config_data',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
