# Generated by Django 5.2 on 2025-05-01 06:20

import django.db.models.deletion
import order.models.customer
import order.models.order
import order.models.price
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('cid', models.BigAutoField(primary_key=True, serialize=False)),
                ('customer_id', models.CharField(default=order.models.customer.get_unique_cusomer_id, max_length=250, unique=True)),
                ('credit_card', models.TextField(blank=True, null=True)),
                ('expiry_year', models.CharField(blank=True, max_length=4, null=True)),
                ('expiry_month', models.CharField(blank=True, max_length=2, null=True)),
                ('street_number', models.CharField(blank=True, max_length=40, null=True)),
                ('street_name', models.TextField(blank=True, null=True)),
                ('country_code', models.CharField(blank=True, max_length=2, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=18, null=True)),
                ('first_name', models.CharField(blank=True, max_length=40, null=True)),
                ('last_name', models.CharField(blank=True, max_length=40, null=True)),
                ('email', models.CharField(blank=True, max_length=40, null=True)),
                ('third_party_id', models.CharField(blank=True, max_length=240, null=True)),
                ('third_party_additional_data', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('pid', models.BigAutoField(primary_key=True, serialize=False)),
                ('price_id', models.CharField(default=order.models.price.get_unique_price_id, max_length=250, unique=True)),
                ('price_point', models.FloatField(default=0.0)),
                ('free_days', models.IntegerField(default=0)),
                ('free_value', models.FloatField(default=0.0)),
                ('plan_duration_days', models.CharField(choices=[('day', 'Daily'), ('week', 'Weekly'), ('month', 'Monthly'), ('year', 'Yearly')], default='month', max_length=10)),
                ('is_primary', models.BooleanField(default=True)),
                ('title', models.CharField(default='Price Title', max_length=140)),
                ('description', models.TextField(default='Description')),
                ('pricing_description', models.TextField(blank=True)),
                ('discount_description', models.TextField(blank=True)),
                ('ordering', models.IntegerField(default=0)),
                ('custom_price_id', models.JSONField(blank=True, default=None, null=True)),
                ('custom_banner_image', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('oid', models.BigAutoField(primary_key=True, serialize=False)),
                ('order_id', models.CharField(default=order.models.order.get_unique_order_id, max_length=250, unique=True)),
                ('order_data', models.JSONField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('cancel_date', models.DateTimeField(blank=True, null=True)),
                ('total_amount_charged', models.FloatField(default=0.0)),
                ('plan_type', models.CharField(choices=[('day', 'Daily'), ('week', 'Weekly'), ('month', 'Monthly'), ('year', 'Yearly')], default='month', max_length=10)),
                ('cancel_requested', models.BooleanField(default=False)),
                ('customer_order_id', models.CharField(blank=True, max_length=240, null=True)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='order.customer')),
                ('order_price', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='order.price')),
            ],
        ),
    ]
